### ISSUE TITLE
Hangfire无法集成

### ISSUE THREAD

**Issue by canyanolGitHub** [52ABP/Home#4]
**描述错误(Describe the bug)**

请尽量将错误描述的清楚而简洁。
(A clear and concise description of what the bug is.)

使用的版本信息：

- ABPCodePowerTools version: 4.1.2

**重现错误信息**

告诉我们是怎么操作的

1. 根据abp 官方集成的文档(.net core 版本)一步一步操作
结果后台作业依旧使用abp自带的后台作业管理,未使用hangfire

**Comment by ltm0203** [comment]
angular的版本，不支持。
